In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression

from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score)

import joblib

In [2]:
df = pd.read_csv("C:/Users/kumar/Downloads/final_ml_data.csv")

In [5]:
df.head()

,PRODUCT_ID,SALE_DATE,SALES_REP,REGION,SALES_AMOUNT,QUANTITY_SOLD,PRODUCT_CATEGORY,UNIT_COST,UNIT_PRICE,CUSTOMER_TYPE,...,MONTH,PROFIT,YEAR,DAY,QUARTER,WEEK,DAY_OF_WEEK,PROFIT_MARGIN,DISCOUNT_AMOUNT,REVENUE_PER_UNIT
0,1052,2023-02-03,Bob,1,5053.97,18,3,152.75,267.22,1,...,2,2060.46,2023,3,1,5,4,40.769138,0.240498,280.776111
1,1093,2023-04-21,Bob,3,4384.02,17,3,3816.39,4209.44,1,...,4,6681.85,2023,21,2,16,4,152.413766,4.630384,257.883529
2,1015,2023-09-21,David,2,4631.23,30,2,261.56,371.40,1,...,9,3295.20,2023,21,3,38,3,71.151724,0.742800,154.374333
3,1072,2023-08-24,Bob,2,2167.94,39,0,4330.03,4467.75,0,...,8,5371.08,2023,24,3,34,3,247.750399,0.893550,55.588205
4,1061,2023-03-24,Charlie,0,3750.20,13,1,637.37,692.71,0,...,3,719.42,2023,24,1,12,4,19.183510,0.554168,288.476923

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   PRODUCT_ID            1000 non-null   int64
 1   SALE_DATE             1000 non-null   object
 2   SALES_REP             1000 non-null   object
 3   REGION                1000 non-null   int64
 4   SALES_AMOUNT          1000 non-null   float64
 5   QUANTITY_SOLD         1000 non-null   int64
 6   PRODUCT_CATEGORY      1000 non-null   int64
 7   UNIT_COST             1000 non-null   float64
 8   UNIT_PRICE            1000 non-null   float64
 9   CUSTOMER_TYPE         1000 non-null   int64
 10  DISCOUNT              1000 non-null   float64
 11  PAYMENT_METHOD        1000 non-null   object
 12  SALES_CHANNEL         1000 non-null   int64
 13  REGION_AND_SALES_REP  1000 non-null   object
 14  MONTH                 1000 non-null   int64
 15  PROFIT                1000 non-null   float64
 16  YEAR                  1000 non-null   int64
 17  DAY                   1000 non-null   int64
 18  QUARTER               1000 non-null   int64
 19  WEEK                  1000 non-null   int64
 20  DAY_OF_WEEK           1000 non-null   int64
 21  PROFIT_MARGIN         1000 non-null   float64
 22  DISCOUNT_AMOUNT       1000 non-null   float64
 23  REVENUE_PER_UNIT      1000 non-null   float64
dtypes: float64(8), int64(12), object(4)
memory usage: 187.6+ KB

In [9]:
y = df["SALES_AMOUNT"]
X = df.drop(columns=["SALE_DATE","SALES_AMOUNT","SALES_REP","PAYMENT_METHOD","REGION_AND_SALES_REP","SALES_REP"],errors="ignore")
print(X.columns)

Index(['PRODUCT_ID', 'REGION', 'QUANTITY_SOLD', 'PRODUCT_CATEGORY',
       'UNIT_COST', 'UNIT_PRICE', 'CUSTOMER_TYPE', 'DISCOUNT', 'SALES_CHANNEL',
       'MONTH', 'PROFIT', 'YEAR', 'DAY', 'QUARTER', 'WEEK', 'DAY_OF_WEEK',
       'PROFIT_MARGIN', 'DISCOUNT_AMOUNT', 'REVENUE_PER_UNIT'],
      dtype='object')

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20,random_state=42)
print("Training Features:", X_train.shape)
print("Testing Features:", X_test.shape)
print("Training Target:", y_train.shape)
print("Testing Target:", y_test.shape)

Training Features: (800, 19)
Testing Features: (200, 19)
Training Target: (800,)
Testing Target: (200,)

In [13]:
lnr_model = LinearRegression()
lnr_model.fit(X_train, y_train)
lnr_predictions = lnr_model.predict(X_test)
print("Linear Regression Results")

print("MAE :", mean_absolute_error(y_test, lnr_predictions))

print("RMSE :", np.sqrt(mean_squared_error(y_test, lnr_predictions)))

print("R2 Score :", r2_score(y_test, lnr_predictions))

Linear Regression Results
MAE : 2373.5621426252205
RMSE : 2677.5166343721453
R2 Score : 0.2242348149985356

In [31]:
rf_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)
rf_predictions = rf_model.predict(X_test)
print("Random Forest Results")

print("MAE :", mean_absolute_error(y_test, rf_predictions))

print("RMSE :", np.sqrt(mean_squared_error(y_test, rf_predictions)))

print("R2 Score :", r2_score(y_test, rf_predictions))

Random Forest Results
MAE : 413.1565569999998
RMSE : 617.6543149745693
R2 Score : 0.9587183649983774

In [33]:
comparison = pd.DataFrame({
    "Model": ["Linear Regression", "Random Forest"],
    "MAE": [
        mean_absolute_error(y_test, lnr_predictions),
        mean_absolute_error(y_test, rf_predictions)
    ],
    "RMSE": [
        np.sqrt(mean_squared_error(y_test, lnr_predictions)),
        np.sqrt(mean_squared_error(y_test, rf_predictions))
    ],
    "R2 Score": [
        r2_score(y_test, lnr_predictions),
        r2_score(y_test, rf_predictions)
    ]
})

comparison

               Model          MAE         RMSE  R2 Score
0  Linear Regression  2373.562143  2677.516634  0.224235
1      Random Forest   413.156557   617.654315  0.958718

In [35]:
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf_model.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

importance

             Feature  Importance
18  REVENUE_PER_UNIT    0.730704
2      QUANTITY_SOLD    0.217459
10            PROFIT    0.011128
16     PROFIT_MARGIN    0.007053
0         PRODUCT_ID    0.005432
17   DISCOUNT_AMOUNT    0.004559
7           DISCOUNT    0.003935
12               DAY    0.003477
5         UNIT_PRICE    0.002599
4          UNIT_COST    0.002525
14              WEEK    0.002400
15       DAY_OF_WEEK    0.001945
1             REGION    0.001485
6      CUSTOMER_TYPE    0.001307
9              MONTH    0.001284
3   PRODUCT_CATEGORY    0.001245
8      SALES_CHANNEL    0.000901
13           QUARTER    0.000557
11              YEAR    0.000006

In [1]:
pip install joblib

Requirement already satisfied: joblib in c:\users\kumar\anaconda3\lib\site-packages (1.4.2)
Note: you may need to restart the kernel to use updated packages.

In [37]:
import joblib

joblib.dump(rf_model, "C:/Users/kumar/Downloads/pre_val.pkl")

['C:/Users/kumar/Downloads/pre_val.pkl']

In [39]:
import joblib

model = joblib.load("C:/Users/kumar/Downloads/pre_val.pkl")

print(model)

RandomForestRegressor(random_state=42)

In [41]:
test_prediction = model.predict(X_test)

print(test_prediction[:5])

[8170.3698  315.8813 5457.8208  849.1206 2251.8792]

In [43]:
prediction_df = pd.DataFrame({
    "Actual Sales": y_test.values,
    "Predicted Sales": rf_predictions
})

prediction_df.head()

   Actual Sales  Predicted Sales
0       7667.96        8170.3698
1        433.40         315.8813
2       5617.64        5457.8208
3        780.27         849.1206
4        848.28        2251.8792

In [47]:
prediction_df.to_csv(
    "C:/Users/kumar/OneDrive/Documents/predicted_sales.csv",
    index=False
)